Words = [
    "apple", "book", "cat", "dog", "egg", "fish", "girl", "hat", "ice", "jump",
    "kite", "lamp", "moon", "nest", "orange", "pen", "queen", "rain", "sun", "tree",
    "umbrella", "vase", "wind", "xray", "yawn", "zebra", "bridge", "cloud", "dream", "flame",
    "globe", "heart", "island", "jungle", "knight", "light", "magic", "ocean", "puzzle", "river",
    "shadow", "tiger", "valley", "whale", "cactus", "dolphin", "eclipse", "fossil", "giraffe", "horizon",
    "banana", "crystal", "dragon", "rocket", "thunder", "magnet", "galaxy", "volcano", "mirror", "tunnel",
    "planet", "blanket", "wizard", "violin", "camera", "marble", "engine", "whisper", "diamond", "robot",
    "ladder", "helmet", "basket", "button", "cobra", "fairy", "shovel", "orbit", "lantern", "scarf",
    "zipper", "anchor", "compass", "scroll", "comet", "bamboo", "feather", "clock", "hammer", "ninja",
    "cookie", "lizard", "pepper", "castle", "ketchup", "spider", "broom", "piano", "trophy", "candle",
    "sailboat", "telescope", "yacht", "xylophone", "quilt", "jigsaw", "sundae", "tornado", "unicorn", "vortex"
]

hints = [
    "A fruit that keeps the doctor away",
    "You read this to gain knowledge",
    "A common pet that meows",
    "A loyal pet that barks",
    "Breakfast food laid by a chicken",
    "Lives in water and swims",
    "A young female human",
    "Worn on your head",
    "Frozen water",
    "An action to get off the ground",
    "A toy that flies in the sky with wind",
    "Used to light a room",
    "Earth's natural satellite",
    "A bird builds this for eggs",
    "A citrus fruit and a color",
    "Used for writing ink on paper",
    "A royal female ruler",
    "Water falling from the sky",
    "A bright star during the day",
    "A tall plant with leaves and branches",
    "Protects you from rain",
    "A decorative container for flowers",
    "Air moving around you",
    "A type of image of your bones",
    "A sound you make when sleepy",
    "A striped animal from Africa",
    "A structure that connects two places",
    "A white thing floating in the sky",
    "What you have when you're sleeping",
    "A small, controlled fire",
    "A model of Earth",
    "A symbol of love",
    "Land surrounded by water",
    "A dense forest with wild animals",
    "A brave warrior in armor",
    "Opposite of dark",
    "Supernatural power or trick",
    "A huge body of salt water",
    "A game or problem to solve",
    "Flowing water in nature",
    "A dark shape caused by blocking light",
    "A big wild cat with stripes",
    "A low area between hills",
    "A large sea creature with a tail",
    "A spiky desert plant",
    "A smart sea mammal",
    "When the sun is blocked",
    "Remains of ancient creatures",
    "A tall animal with a long neck",
    "Where sky and earth meet",
    "A yellow fruit with a peel",
    "A shiny clear stone or solid",
    "A fire-breathing creature",
    "Flies to space",
    "Loud sound during storms",
    "Attracts metal objects",
    "A huge system of stars",
    "A mountain that erupts lava",
    "Shows your reflection",
    "A passage under the ground",
    "A large object in space",
    "Used to keep you warm",
    "A magical old man",
    "A musical instrument with strings",
    "Takes pictures",
    "A round decorative stone",
    "Powers cars or machines",
    "Talking very quietly",
    "A shiny precious stone",
    "A machine that can do tasks",
    "Used to climb high places",
    "Worn for head protection",
    "Used to carry things",
    "A small fastener or control",
    "A snake with a hood",
    "A small magical creature",
    "Used to dig",
    "The path of planets",
    "Used to light dark places",
    "Worn around the neck",
    "A fastener on clothes",
    "Keeps a ship in place",
    "Shows direction",
    "An ancient rolled-up paper",
    "A ball of ice and rock in space",
    "A type of fast-growing plant",
    "Soft part of a bird",
    "Tells time",
    "Used to hit nails",
    "A silent stealthy warrior",
    "A sweet baked snack",
    "A small reptile",
    "A spicy seasoning",
    "A big building with towers",
    "A tomato-based condiment",
    "A creepy crawling insect",
    "Used by witches to fly",
    "A large keyboard instrument",
    "A prize or award",
    "Gives light when lit",
    "A boat with a sail",
    "Used to see far away",
    "A luxury boat",
    "A musical instrument with bars",
    "A thick blanket",
    "A puzzle with interlocking pieces",
    "Ice cream with toppings",
    "A violent rotating storm",
    "A horse with a horn",
    "A swirling air current"
]
